version: "3.9"

services:
  db:
    ports:
      - "8454:5432"
  web:
    build:
      dockerfile: Dockerfile-local
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:4445"
    ports:
      - "4445:4445"