# Generated by Django 4.0.4 on 2022-05-02 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='serial number')),
                ('acquisitioned_at', models.DateField(blank=True, null=True, verbose_name='date of acquisition')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='warranty start')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='warranty finnish')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.category', verbose_name='category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.location', verbose_name='location')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.model', verbose_name='model')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.tag', verbose_name='label')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
    ]
